sudo: required
os:
  - linux
  - osx

install:
    - scripts/travis.bash update
    - scripts/travis.bash dependencies

before_script:
    # The version output of vimpager depends of the tags in the repository so
    # we need to fetch them before running the tests.  Currently all tags are
    # fetched.  TODO: Only fetch the latest tag.
    - git fetch --unshallow --tags


script:
    - scripts/travis.bash install-deb
    - scripts/travis.bash lint
    - make all
    - make test
    - make install
    - test "$(which vimpager)" = /usr/local/bin/vimpager

# vim: sw=4
